### ISSUE TITLE
Officer object has no attribute case_numbers

### ISSUE THREAD

**Issue by benlk** [INN/cpd-settlements#2]
When running get_data.py to acquire the project data.

```
$ ./get_data.py
Traceback (most recent call last):
  File "./get_data.py", line 4, in <module>
    from lib.geocode_addresses import geocode_addresses
  File "/Users/blk/tarbell/cpd_settlements/lib/geocode_addresses.py", line 4, in <module>
    from inc.models import Case
  File "/Users/blk/tarbell/cpd_settlements/inc/models.py", line 150, in <module>
    case.officers = case.get_related_officers()
  File "/Users/blk/tarbell/cpd_settlements/inc/models.py", line 62, in get_related_officers
    if self.case_number in officer.case_numbers:
AttributeError: 'Officer' object has no attribute 'case_numbers'
```

**Comment by benlk** [comment]
Commenting out the `# Do some heavy lifting up-front so this stuff gets stashed in memory` section in inc/models.py fixes this, so I'm guessing that it's a problem with the data that we're attempting to load not yet existing on an initial setup of the file.

**Comment by benlk** [comment]
After loading data, this and similar errors show up, which means to me that it's probably just a difference in assumptions between the new data and the old project code. Tentatively closing, as this is fixed in the  branch ben-first-load-fixes. https://github.com/INN/cpd-settlements/tree/ben-first-load-fixes
